### ISSUE TITLE
not work without NODE_TLS_REJECT_UNAUTHORIZED = 0 

### ISSUE THREAD

**Issue by jeeteshnariya** [zerodha/kiteconnectjs#32]
there are no response error when web-socket ticker run

**Comment by jeeteshnariya** [comment]
it work after 
NODE_TLS_REJECT_UNAUTHORIZED = 0

**Comment by vishnus** [comment]
Hi @jeeteshnariya you should upgrade Node.js version. Current running version of Node.js is 12. This issue is because of an old root CA certificate expired on May 30th that affects old systems that are not updated with new root CAs. More about it: https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT
