### ISSUE TITLE
can't resolve 'querystring'

### ISSUE THREAD

**Issue by waifo** [zerodha/kiteconnectjs#67]
Compiled with problems:X

ERROR in ./node_modules/kiteconnect/lib/connect.js 9:18-40

Module not found: Error: Can't resolve 'querystring' in 'D:\Project\node_modules\kiteconnect\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
	- install 'querystring-es3'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "querystring": false }
	
I see 'querystring' is used in kiteconnect but is not included in dependency in the project

**Comment by vividvilla** [comment]
What node version you are using?

**Comment by vividvilla** [comment]
I guess you are trying to compile this to JS for frontend but this lib supports only Node JS.

**Comment by karan-git** [comment]
1. Install this package - npm i query-string. (because old querystring version does't support with node 5 or above version).
2. Goto this path - node_module/kiteconnect/lib/connect.js.
3. replace var querystring = require("querystring"); to var querystring = require("query-string");
4. Run server again.
